export const LOADING_HABITUES = 'LOAD_HABITUES';
export const LOADED_HABITUES = 'LOADED_HABITUES';
export const LOADED_FAILURE_HABITUES = 'LOADED_FAILURE_HABITUES';
export const PUSHING_HABITUE = 'PUSHING_HABITUE';
export const PUSHED_HABITUES = 'PUSHED_HABITUES';
export const PUSHED_FAILURE_HABITUES = 'PUSHED_FAILURE_HABITUES';